#######################################################################
# Apple TV ruleset
#######################################################################
DOMAIN-SUFFIX,play.itunes.apple.com
DOMAIN-SUFFIX,play-edge.itunes.apple.com
DOMAIN-SUFFIX,play-edge.apple.com
DOMAIN-SUFFIX,tv.apple.com
DOMAIN-SUFFIX,itunes.apple.com
DOMAIN-SUFFIX,mzstatic.com
DOMAIN-SUFFIX,aaplimg.com
