#######################################################################
# Apple TV ruleset
#######################################################################
DOMAIN-SUFFIX,play.itunes.apple.com
DOMAIN-SUFFIX,play-edge.itunes.apple.com
DOMAIN-SUFFIX,play-edge.apple.com
# Apple TV 应用首页、节目列表、详情页
DOMAIN-SUFFIX,tv.apple.com
# Store API、影片元数据、购买信息
DOMAIN-SUFFIX,itunes.apple.com
# 海报、图片、字幕、CSS、JS 等静态资源
DOMAIN-SUFFIX,mzstatic.com
# Apple 图片/CDN 静态资源
DOMAIN-SUFFIX,aaplimg.com
DOMAIN-SUFFIX,videos.apple.com
DOMAIN-SUFFIX,xp.apple.com
DOMAIN,sps-media.apple.com
