# Nintendo Account
DOMAIN-SUFFIX,nintendo.com
DOMAIN-SUFFIX,accounts.nintendo.com
DOMAIN-SUFFIX,api.accounts.nintendo.com
DOMAIN-SUFFIX,cdn.accounts.nintendo.com

# Nintendo Network
DOMAIN-SUFFIX,nintendo.net
DOMAIN-SUFFIX,nintendowifi.net

# eShop / CDN
DOMAIN-SUFFIX,eshop.nintendo.net
DOMAIN-SUFFIX,cdn.nintendo.net
DOMAIN-SUFFIX,baas.nintendo.com

# Switch CDN
DOMAIN-SUFFIX,d4c.nintendo.net
DOMAIN-SUFFIX,dragons.nintendo.net

# Switch 游戏内容（BCAT）
DOMAIN-SUFFIX,bcat-topics-lp1.cdn.nintendo.net
DOMAIN-SUFFIX,bcat-list-lp1.cdn.nintendo.net
DOMAIN-SUFFIX,bcat-data-lp1.cdn.nintendo.net
DOMAIN-SUFFIX,bcat-web-lp1.cdn.nintendo.net

# 连接测试
DOMAIN-SUFFIX,ctest.cdn.nintendo.net

# Device / Application Authentication
DOMAIN-SUFFIX,ndas.srv.nintendo.net

# Push / Notifications
DOMAIN-SUFFIX,npns.srv.nintendo.net

# Nintendo Switch Online
DOMAIN-SUFFIX,nso.nintendo.net
