# Steam 商店、社区、登录、好友、创意工坊规则，排除游戏下载、更新

# 登录
DOMAIN-SUFFIX,steamserver.net
DOMAIN-SUFFIX,steamcommunity.com
DOMAIN-SUFFIX,steampowered.com
DOMAIN-SUFFIX,steamstatic.com
DOMAIN-SUFFIX,steam-chat.com

# API
DOMAIN-SUFFIX,steam-api.com
DOMAIN-SUFFIX,steamapis.com

# Valve
DOMAIN-SUFFIX,valvesoftware.com
DOMAIN-SUFFIX,valve.net

# Steam 中国偶尔也会访问
DOMAIN-SUFFIX,steamchina.com
